name: Sync to 46009361.com
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: source
      - uses: actions/checkout@v3
        with:
          repository: 46009361/46009361.com
          path: target
          token: ${{ secrets.GH_TOKEN }}
      - run: |
          cp -r source/* target/flying-game/
          cd target
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add flying-game
          git commit -m "${{ github.event.head_commit.message }}" || true
          git push